### ISSUE TITLE
vc bot not working

### ISSUE THREAD

**Issue by Kingston95** [infamouskoala/koalavc#1]
The python file opens up but then closes instantly after do u have any idea how to fix?

**Comment by infamouskoala** [comment]
try running it in command prompt so u can see the error, I am guessing u haven't installed the modules or the right discord version

**Comment by Kingston95** [comment]
i use the browser version of discord and i cant seem to run in command prompt do you know how lol cause im stupid

**Comment by infamouskoala** [comment]
i mean run the python script in cmd, open cmd in the folder that u have the `main.py` inside of and then do `py main.py`

**Comment by Kingston95** [comment]
![image](https://github.com/infamous-koala/koalavc/assets/132428066/6b826cc5-ba44-4406-82c0-d3bfca83b190)

**Comment by infamouskoala** [comment]
as i said, u need to open cmd in the folder that u saved the files in

edit: solved over at discord, didnt had discord and flask installed.
